# Generated by Django 4.2.3 on 2023-10-03 16:19

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import ekartapp.models
import galleryapp.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0003_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand_url', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('logo', models.ImageField(upload_to=ekartapp.models.RandomFileName('Ekart_brand_logo'), validators=[galleryapp.validators.validate_file_size])),
                ('website', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ekart Brand',
                'verbose_name_plural': 'Ekart Brands',
            },
        ),
        migrations.CreateModel(
            name='EkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ecategory_url', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekcategories', to='productapp.category')),
            ],
            options={
                'verbose_name': 'Ekart Category',
                'verbose_name_plural': 'Ekart Categories',
            },
        ),
        migrations.CreateModel(
            name='EkProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ekartapp.models.RandomFileName('ekart_products'), validators=[galleryapp.validators.validate_file_size])),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_url', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekart_products', to='ekartapp.ekbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekart_products', to='ekartapp.ekcategory')),
            ],
            options={
                'verbose_name': 'Ekart Product',
                'verbose_name_plural': 'Ekart products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_Image', models.ImageField(upload_to=ekartapp.models.RandomFileName('ekart_productlist'), validators=[galleryapp.validators.validate_file_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekart_productImages', to='ekartapp.ekproduct')),
            ],
            options={
                'verbose_name': 'Ekart Product Image',
                'verbose_name_plural': 'Ekart Product Images',
            },
        ),
        migrations.CreateModel(
            name='EkSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('esubcategory_url', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eksubcategory', to='ekartapp.ekcategory')),
            ],
            options={
                'verbose_name': 'Ekart Category',
                'verbose_name_plural': 'Ekart Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='ekproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ekart_products', to='ekartapp.eksubcategory'),
        ),
        migrations.AddField(
            model_name='ekbrand',
            name='category',
            field=models.ManyToManyField(related_name='brand', to='ekartapp.ekcategory'),
        ),
    ]
