# Generated by Django 4.2.3 on 2023-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='EkProductImage',
        ),
    ]
