# Generated by Django 4.2.3 on 2023-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='Category', to='productapp.brand'),
        ),
    ]
