# Generated by Django 4.2.3 on 2023-07-27 15:42

from django.db import migrations, models
import galleryapp.models
import galleryapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=galleryapp.models.RandomFileName('gallery'), validators=[galleryapp.validators.validate_file_size]),
        ),
    ]
