# Generated by Django 4.2.3 on 2023-07-29 03:04

import carouselapp.models
from django.db import migrations, models
import galleryapp.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=carouselapp.models.RandomFileName('carousel'), validators=[galleryapp.validators.validate_file_size])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
