# Generated by Django 4.2.3 on 2023-07-27 15:42

import carouselapp.models
from django.db import migrations, models
import galleryapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('carouselapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=carouselapp.models.RandomFileName('carousel'), validators=[galleryapp.validators.validate_file_size]),
        ),
    ]
